version: "3"

services:
  db:
    image: postgres:12.5
    environment:
      POSTGRES_PASSWORD: graduatenu
    volumes:
      - graduatenu_data:/var/lib/postgresql/data
    networks:
      - sub-etha
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    networks:
      - sub-etha
    image: "frontend"
  backend:
    environment:
      RAILS_ENV: production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: graduatenu
      POSTGRES_HOST: db
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: ./Dockerfile.prod
    networks:
      - sub-etha
    image: "backend"
  revproxy:
    depends_on:
      - frontend
      - backend
    restart: always
    build:
      context: .
      dockerfile: ./common/Dockerfile
    networks:
      - sub-etha
    ports:
      - "443:443"
      - "80:80"
    image: "revproxy"
    volumes:
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/var/www/certbot
  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email graduatenu@outlook.com --agree-tos --no-eff-email -d graduatenu.khoury.northeastern.edu
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/var/www/certbot

networks:
  sub-etha:

volumes:
  graduatenu_data:
