version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: graduatenu
    volumes:
      - graduatenu_dbdata:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 80 -b '0.0.0.0'"
    volumes:
      - .:/api
    ports:
      - "3001:80"
    depends_on:
      - db
volumes:
  graduatenu_dbdata:
