name: CI

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "13"]
    name: Node ${{ matrix.node }} compatibility
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Run Jest Tests
        run: |
          yarn install
          yarn test
  build-frontend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image for frontend
        run: |
          docker build -t frontend -f frontend/Dockerfile .
  build-api-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image for api
        run: |
          cd api
          docker build -f Dockerfile.dev -t api .
